version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      build: kc-standalone
      #image: jboss/keycloak
      environment: 
        MYSQL_ADDR: mysql
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        #KEYCLOAK_LOGLEVEL: DEBUG
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8090:8080
      depends_on:
        - mysql
